name: Publish to the Factorio mod portal

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Publish mod
        uses: Penguin-Spy/factorio-mod-portal-publish@main
        with:
          factorio-api-key: ${{ secrets.FACTORIO_API_KEY }}